export const API_ROUTES = {
  JINA: {
    LINK_PREVIEW: "/jina/link-preview",
  },
  OFFERS: {
    BASE: "/offers",
    ALL: "/offers/all",
    BATCH: "/offers/batch",
    MY_OFFERS: "/offers/my-offers",
    BY_ID: (id: string | number) => `/offers/${id}`,
    BY_SLUG: (slug: string) => `/offers/slug/${slug}`,
    EXCEPT_ID: (id: string | number) => `/offers/all-except/${id}`,
    BY_VITRINE_SLUG: (slug: string) => `/offers/vitrine/${slug}`,
    BY_VITRINE_SLUG_EXCEPT_ID: (slug: string, id: string | number) =>
      `/offers/vitrine/${slug}/all-except/${id}`,
  },
  STORES: {
    BASE: "/stores",
    BY_ID: (id: string | number) => `/stores/${id}`,
  },
  CATEGORIES: {
    BASE: "/categories",
    BY_ID: (id: string | number) => `/categories/${id}`,
  },
  RETAIL_STORES: {
    BASE: "/retail-stores",
    BY_ID: (id: string | number) => `/retail-stores/${id}`,
  },
  VENDOR_STORES: {
    BASE: "/vendor-stores",
    BY_ID: (id: string | number) => `/vendor-stores/${id}`,
    ME: "/vendor-stores/me",
  },
  USERS: {
    BASE: "/users",
    ME: "/users/me",
    PROFILE: "/users/profile",
    PROFILE_INTEGRATIONS: "/users/profile/integrations",
    REGISTER: "/users",
    LEGACY_REGISTER: "/users/register",
    ADMIN_CREATE: "/users/admin/create",
    BY_ID: (id: string | number) => `/users/${id}`,
    SET_PASSWORD: (id: string | number) => `/users/${id}/set-password`,
    CHANGE_PASSWORD: "/users/change-password",
    RESET_PASSWORD_REQUEST: "/users/reset-password-request",
    RESET_PASSWORD: "/users/reset-password",
    SET_FIRST_PASSWORD: "/users/set-first-password",
  },
  VITRINES: {
    BASE: "/vitrines",
    SELECT: "/vitrines/select",
    BY_USER_ID: "/vitrines/me",
    BY_ID: (id: string | number) => `/vitrines/${id}`,
    BY_SLUG: (slug: string) => `/offers/vitrine/${slug}`,
    UPDATE_IMAGE: (id: string | number) => `/vitrines/${id}/image`,
  },
  AUTH: {
    BASE: "/auth",
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
  },
  DASHBOARD: {
    BASE: "/dashboard",
    ME: "/dashboard/me",
    ADMIN: "/dashboard/admin",
  },
  WHATSAPP: {
    CONNECT: "/whatsapp/connect",
    STATUS: "/whatsapp/status",
    DISCONNECT: "/whatsapp/disconnect",
    SETUP_WEBHOOK: (instanceName: string) => `/whatsapp/webhook/setup/${instanceName}`,
    GROUPS: (instanceName: string) => `/whatsapp/groups/${instanceName}`,
    SYNC_GROUPS: (instanceName: string) => `/whatsapp/groups/${instanceName}/sync`,
    CHECK_CAPACITY: (instanceName: string) => `/whatsapp/groups/${instanceName}/check-capacity`,
    EXPAND_GROUP: (id: number) => `/whatsapp/groups/${id}/expand`,
    GROUP_CONFIG: (id: number) => `/whatsapp/groups/${id}/config`,
    PAIR_GROUPS: "/whatsapp/groups/pair",
    UNPAIR_GROUP: (id: number) => `/whatsapp/groups/${id}/unpair`,
    GROUP_DONORS: (id: number) => `/whatsapp/groups/${id}/donors`,
    SETTINGS: (instanceName: string) => `/whatsapp/settings/${instanceName}`,
    QUEUE: (instanceName: string) => `/whatsapp/queue/${instanceName}`,
    QUEUE_APPROVE: (id: number) => `/whatsapp/queue/${id}/approve`,
    QUEUE_REJECT: (id: number) => `/whatsapp/queue/${id}/reject`,
    QUEUE_EDIT: (id: number) => `/whatsapp/queue/${id}`,
    INVITE_LINK: (id: number) => `/whatsapp/groups/${id}/invite-link`,
    FAMILY: (id: number) => `/whatsapp/groups/${id}/family`,
  },
  SHOPEE: {
    REPORTS: {
      CONVERSIONS: "/shopee/reports/conversions",
      VALIDATED: "/shopee/reports/validated",
    },
  },
};
